<a href="https://colab.research.google.com/github/xcl-esc/Analise_Airbnb/blob/main/analise_descritiva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
cd /content/drive/MyDrive/analise_de_dados/Testes

/content/drive/MyDrive/analise_de_dados/Testes

In [7]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('dados_limpos.csv')
df.shape

(19427, 17)

In [9]:
df.describe()

,id,scrape_id,accommodates,bathrooms,bedrooms,beds,price,review_scores_rating,review_scores_accuracy
count,1.942700e+04,1.942700e+04,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000,15569.000000,15564.000000
mean,7.830437e+17,2.025062e+13,3.967159,1.486462,1.510527,2.354043,685.877284,4.808593,4.823135
std,5.537916e+17,6.093907e-01,2.301538,0.964185,0.992316,2.107319,2922.144662,0.355084,0.349307
min,1.787800e+04,2.025062e+13,1.000000,0.000000,0.000000,0.000000,39.000000,1.000000,1.000000
25%,4.737128e+07,2.025062e+13,2.000000,1.000000,1.000000,1.000000,200.000000,4.760000,4.790000
50%,1.000087e+18,2.025062e+13,4.000000,1.000000,1.000000,2.000000,311.000000,4.920000,4.930000
75%,1.286474e+18,2.025062e+13,5.000000,2.000000,2.000000,3.000000,560.000000,5.000000,5.000000
max,1.450231e+18,2.025062e+13,16.000000,16.000000,27.000000,52.000000,225000.000000,5.000000,5.000000

In [10]:
df['accommodates'].unique()

array([ 5,  2,  4,  1,  6,  8,  3, 15, 14, 12, 10,  7,  9, 16, 13, 11])

In [11]:
df['accommodates'].value_counts().sort_index()

accommodates
1      746
2     5286
3     2442
4     5841
5     1460
6     2011
7      334
8      566
9       83
10     274
11      24
12     135
13      11
14      39
15      30
16     145
Name: count, dtype: int64

In [12]:
df['accommodates'].value_counts().sort_values()

accommodates
13      11
11      24
15      30
14      39
9       83
12     135
16     145
10     274
7      334
8      566
1      746
5     1460
6     2011
3     2442
2     5286
4     5841
Name: count, dtype: int64

Aqui se pode ver que os imóveis que comportam de 2 a 6 pessoas são a esmagadora maioria dos imóveis. Sendo que de 2 a 4 pessoas já representa praticamente 60% do dataset.

In [13]:
df['accommodates'].value_counts(normalize=True).sort_values() * 100

accommodates
13     0.056622
11     0.123539
15     0.154424
14     0.200752
9      0.427240
12     0.694909
16     0.746384
10     1.410408
7      1.719257
8      2.913471
1      3.840016
5      7.515314
6     10.351573
3     12.570134
2     27.209554
4     30.066402
Name: proportion, dtype: float64

Agora comparamos o número de acomodações com o número de quartos, observando o seguinte cenário: acomodação barata, 1 quarto acomoda 4 pessoas. Não seria uma boa experiência.

In [14]:
pd.crosstab(df['accommodates'], df['bedrooms'])

bedrooms,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,16.0,26.0,27.0
accommodates,,,,,,,,,,,,,,,,,,
1,26,693,19,5,3,0,0,0,0,0,0,0,0,0,0,0,0,0
2,314,4806,133,22,6,2,2,0,0,0,1,0,0,0,0,0,0,0
3,173,2004,247,12,1,0,2,2,0,0,0,1,0,0,0,0,0,0
4,181,3347,2192,110,8,1,0,0,0,0,1,0,0,0,0,0,1,0
5,35,407,790,224,4,0,0,0,0,0,0,0,0,0,0,0,0,0
6,22,234,883,834,38,0,0,0,0,0,0,0,0,0,0,0,0,0
7,3,27,97,180,25,1,0,1,0,0,0,0,0,0,0,0,0,0
8,4,32,117,264,135,12,2,0,0,0,0,0,0,0,0,0,0,0
9,0,5,10,39,21,8,0,0,0,0,0,0,0,0,0,0,0,0
10,3,25,35,79,66,59,6,0,0,0,1,0,0,0,0,0,0,0
11,0,0,3,9,5,6,1,0,0,0,0,0,0,0,0,0,0,0
12,0,9,12,29,39,26,20,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,2,4,1,4,0,0,0,0,0,0,0,0,0,0,0
14,0,1,2,4,9,8,10,5,0,0,0,0,0,0,0,0,0,0
15,0,4,2,5,5,6,6,1,0,0,0,0,0,1,0,0,0,0
16,16,26,4,11,19,27,12,13,6,3,3,1,1,0,1,1,0,1

A tabela acima também pode revelar coisas como cidades amistosas para visitantes em eventos como shows e afins, em geral estadias muito curtas. Num primeiro momento 0 quartos que acomodam até 4 pessoas são bem comuns, aparentemente.

Possíveis insights:
<br></br>-Pessoa sozinha que vai pra um show/virada de ano ou algo assim serviria um imovel sem quarto com 1 cama/sofa cama e tem muitos imoveis com essa possibilidade
<br></br>-Pessoa sozinha pra estadia superior a 1 dia precisaria de pelo menos 1 quarto entao ja corta imoveis nessa conta.
<br></br>-1 quarto pra 2 ou 3 pessoas tem bastante ocorrencia

Agora cruzando as tabelas accommodates e bedrooms para entender a média de preços e assim provar se realmente valem a pena esses imóveis pelos preços.

In [15]:
pd.crosstab(df['accommodates'], df['bedrooms'], values=df['price'], aggfunc='mean').round(2)

bedrooms,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,16.0,26.0,27.0
accommodates,,,,,,,,,,,,,,,,,,
1,530.46,344.73,868.37,231.80,150.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,269.61,399.49,385.93,507.32,372.83,279.00,475.50,NaN,NaN,NaN,225.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,255.16,456.73,527.39,589.58,171.00,NaN,207.00,112.00,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,NaN
4,300.91,406.82,739.15,1016.65,1447.75,60.00,NaN,NaN,NaN,NaN,200.00,NaN,NaN,NaN,NaN,NaN,178.0,NaN
5,305.91,374.84,719.84,1088.71,2045.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,607.14,604.18,932.00,1244.37,1909.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,291.00,357.07,557.40,975.43,2245.72,27389.00,NaN,150.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1033.50,587.22,695.91,1554.06,2927.56,4502.58,3400.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,587.20,604.00,941.03,1361.05,5720.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1466.67,4897.44,1221.83,1122.05,2795.00,8646.00,6733.17,NaN,NaN,NaN,1000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,1016.33,926.78,3989.00,2668.83,723.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,1276.67,421.75,816.41,2927.08,5971.92,4973.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,995.50,3030.50,3040.00,3056.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,950.00,490.00,2361.75,1728.56,2682.50,2624.00,3668.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,90.00,3450.00,1272.60,2357.00,2042.83,3036.00,8990.00,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN
16,2227.25,2106.38,1212.75,1480.91,3502.89,4821.93,3324.50,5106.62,10418.33,8406.0,10475.67,329.0,16500.0,NaN,45000.0,2029.0,NaN,76.0

In [16]:
df[(df['bedrooms'] == 0) & (df['accommodates'] == 1)]['price'].max()
#Aqui identifico um outlier que faz com que a média de preço de lofts para uma pessoa suba muito

5000.0

In [17]:
#Calculando pela mediana para valores mais fieis
pd.crosstab(df['accommodates'], df['bedrooms'], values=df['price'], aggfunc='median').round(2)

bedrooms,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,16.0,26.0,27.0
accommodates,,,,,,,,,,,,,,,,,,
1,159.0,139.0,199.0,124.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201.0,233.0,279.0,252.5,340.0,279.0,475.5,NaN,NaN,NaN,225.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,213.0,246.0,369.0,426.5,171.0,NaN,207.0,112.0,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,NaN
4,218.0,279.0,472.0,697.0,1100.0,60.0,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,NaN,NaN,178.0,NaN
5,225.0,276.0,449.5,684.0,469.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,440.5,257.0,492.0,755.0,1706.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,301.0,294.0,442.0,707.5,1291.0,27389.0,NaN,150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,293.0,161.5,440.0,769.0,1386.0,3000.0,3400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,507.0,420.0,774.0,1345.0,2631.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1350.0,166.0,366.0,800.0,1600.0,5615.0,6925.0,NaN,NaN,NaN,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,1200.0,929.0,729.0,2556.5,723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,192.0,254.0,679.0,1283.0,4151.5,3424.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,995.5,1726.0,3040.0,2078.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,950.0,490.0,1043.0,889.0,1735.0,1701.0,3426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,90.0,3450.0,1408.0,1350.0,2100.5,2160.0,8990.0,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN
16,1854.5,206.5,165.0,858.0,1702.0,3680.0,2377.0,3440.0,8581.5,8109.0,12000.0,329.0,16500.0,NaN,45000.0,2029.0,NaN,76.0

In [18]:
df[(df['bedrooms'] == 4) & (df['accommodates'] == 3)]['price'].min()

171.0

In [19]:
df[(df['bedrooms'] == 4) & (df['accommodates'] == 3)]['price'].max()

171.0

Para viajantes sozinhos, em dupla e até em trio de rápida estadia a taxa de preços é até favorável. Mas também é possível perceber que imoveis com 1 quarto que acomode a mesma quantidade de pessoas não é tão distante em preços e pode ser até mais barato para 1 pessoa, do que um loft/estúdio.

Da mesma forma podemos avaliar que partindo do princípio que para viajens em família ou amigos (entre 3 e 5 pessoas), e que 2 quartos seria o mínimo de conforto, os preços tendem a variar muito de acordo com a quantidade de pessoas e de quartos, mas com apenas 2 quartos é onde tem os menores preços. Além de que há poucos imóveis nessa faixa de acomodações.

In [20]:
familia_2_quartos = df[(df['accommodates'].between(3,5)) & (df['bedrooms'] == 2)]
print(f"Total de imóveis para entre 3 e 5 pessoas com 2 quartos: {len(familia_2_quartos)}")

Total de imóveis para entre 3 e 5 pessoas com 2 quartos: 3229